client_frontend:
  build: .
  ports:
    - "0.0.0.0:3000:3000"
    - "0.0.0.0:3001:3001"
    - "0.0.0.0:5000:5000"
  environment:
    WEBSITE_HOSTNAME: "0.0.0.0:5000"
  volumes:
    - .:/home/client_frontend
  log_driver: "json-file"
  log_opt:
    max-size: "10k"
    max-file: "5"
